name: Compat Contracts

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Install project
        run: uv sync --extra benchmark
      - name: Run stdlib compat parity
        run: uv run pytest tests/test_compat_parity.py
      - name: Run CPython contract suites
        env:
          PYTHONWARNINGS: "ignore::DeprecationWarning"
        run: uv run pytest tests/test_cpython_contracts.py
