# This workflow publishes the package to PyPI whenever a version tag is pushed.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Build distributions with Hatch
        run: uvx --python 3.14 hatch build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: hatch-dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-artifacts
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/project/unirun/${{ github.ref_name }}
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: hatch-dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
